### ISSUE TITLE
Appium 1.5 Support

### ISSUE THREAD

**Issue by aarongrider** [appium/python-client#105]
It seems a few methods in this client are lacking support for the new beta of Appium 1.5 including...
-Setting orientation
-Getting screenshots
-Removing apps

I am getting an error when trying to do any of these tasks.

```
info: [MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAABgAAAAgACAYAAADg0fg2AAAAAXNSR0IArs4c6QAAQABJREFUeAHsnQmgbVP9x9cd3kOlNJhVykySIWPqZR4LRYP+mkSUigYayJQSKhqoSIMpZSiKSIRCNJASIk...
info: [HTTP] <-- GET /wd/hub/session/3236246a-1310-4b71-b489-c4e26c74924e/screenshot 200 14033.190 ms - 2806146 
info: [HTTP] --> POST /wd/hub/session/3236246a-1310-4b71-b489-c4e26c74924e/element {"using":"name","sessionId":"3236246a-1310-4b71-b489-c4e26c74924e","value":"Listen"}
info: [debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":["using","value"]} and you sent ["using","sessionId","value"]
info: [HTTP] <-- POST /wd/hub/session/3236246a-1310-4b71-b489-c4e26c74924e/element 400 1.366 ms - 110 
```

```
Removing app...
info: [HTTP] --> POST /wd/hub/session/3236246a-1310-4b71-b489-c4e26c74924e/appium/device/remove_app {"sessionId":"3236246a-1310-4b71-b489-c4e26c74924e","appId":"com.subsplashconsulting.inspiration"}
info: [debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"required":[["appId"],["bundleId"]]} and you sent ["sessionId","appId"]
info: [HTTP] <-- POST /wd/hub/session/3236246a-1310-4b71-b489-c4e26c74924e/appium/device/remove_app 400 1.782 ms - 109 
```

**Comment by imurchie** [comment]
Thanks for catching this! I have fixed it on the server and will cut a new version of the beta.

**Comment by aarongrider** [comment]
Awesome! Works a lot better now. I think there might still be a few methods still missing session id

```
info: [HTTP] <-- POST /wd/hub/session/9b5d66ce-bc4d-4df7-b53c-9e9719e0e546/element 200 1323.641 ms - 87 
info: [HTTP] --> POST /wd/hub/session/9b5d66ce-bc4d-4df7-b53c-9e9719e0e546/touch/perform 
info: [debug] [MJSONWP] Bad parameters: BadParametersError: Parameters were incorrect. We wanted {"wrap":"gestures","required":["gestures"]} and you sent ["sessionId","actions"]
```

Do you want me to do a full audit / pull request?

**Comment by imurchie** [comment]
I should make some unit tests on the server. Not sure why `/touch/perform` is not being handled.

**Comment by imurchie** [comment]
Update Python client to `0.19` which should fix the touch action problem.
